export const CONSTANTS = {
  SERVER_ERROR: "Hệ thống đang bảo trì",
};

export const SOCKET_CONSTANTS = {
  JOIN: "JOIN",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  TYPING: "TYPING",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
  ACK_MESSAGE: "ACK_MESSAGE",
};
