export const CONSTANTS = {
  SERVER_ERROR: "Hệ thống đang bảo trì",
};

export const SOCKET_CONSTANTS = {
  JOIN: "JOIN",
  USER_CONNECT: "USER_CONNECT",
  USER_DISCONNECT: "USER_DISCONNECT",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  GET_USER_ONLINE: "GET_USER_ONLINE",
};
